# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170619_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='room_id',
            new_name='room',
        ),
    ]
