# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170619_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='fixed'),
        ),
    ]
