# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ticket_fixed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fixed',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='subject',
        ),
    ]
