# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170621_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
