# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20170621_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('building', 'user', 'number')]),
        ),
    ]
