# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170621_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('building', 'number')]),
        ),
    ]
