# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170621_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
