# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_building_room_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='building_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='room_id',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
