# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170505_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allow_delete',
            field=models.BooleanField(default=False, verbose_name='allow_delete'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
